python training.py \
  --mode single \
  --device cuda:0 \
  --episodes 10 \
  --max-steps 1000 \
  --output-dir /tmp/mprl-variable-replay-smoke \
  --replay-warmup-size 1 \
  --micro-batch-size 2 \
  --gradient-accumulation-steps 2 \
  --checkpoint-every 2 \
  --no-resume-logs \
  --log-level INFO
