python training.py \
  --mode single \
  --device cuda:0 \
  --episodes 1000 \
  --max-steps 100 \
  --output-dir /tmp/mprl-dataset-folder-smoke \
  --replay-warmup-size 1000 \
  --micro-batch-size 16 \
  --gradient-accumulation-steps 4 \
  --checkpoint-every 128 \
  --no-resume-logs \
  --validate-every 1 \
  --log-level INFO \
  --observation-encoder esm2 \
  --esm2-device cuda:0 \
  --keep-cleaned-pdbs \
  --pdb-dir /mnt/nas/jianquanzhao/data/mprl/outputs/cleaned_pdb_debug \
  --epochs 10 \
  --episodes-per-epoch 1024 \
  --train-batch-size 64 \
